spring:
  application:
    name: task-manager
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: validate
    show-sql: false
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  liquibase:
    contexts: ${ENV}
    change-log: classpath:/db/liquibase/master.yaml

task-manager:
  env: ${ENV}
  openapi:
    dev-url: ${OPENAPI_DEV_URL}
    prod-url: ${OPENAPI_PROD_URL}